default: &default
  adapter: postgresql
  encoding: unicode
  database: rsociety
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432


development:
  <<: *default
  database: rsociety


test:
  <<: *default
  database: rsociety

production:
  <<: *default
  database: rsociety

